version: "3.9"

services:
  app:
    build: .
    container_name: backend-app
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Bangkok
      # (tuỳ chọn) nếu bạn cần chạy profile prod
      # SPRING_PROFILES_ACTIVE: prod
    volumes:
      - ./secret.yml:/app/secret.yml:ro