spring:
  datasource:
    url: <your_dtb_url>
    username: <your_username>
    password: <your_password>
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        connection:
          characterEncoding: UTF-8
          charSet: UTF-8
cloudinary:
  cloud_name: your_cloud_name
  api_key: your_api_key
  api_secret: your_secret

jwt:
  signerKey: your_secret_key