spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dams?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_vietnamese_ci&serverTimezone=UTC
    username: root
    password: bach2612
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        connection:
          characterEncoding: UTF-8
          charSet: UTF-8

  config:
    import: optional:file:secret.yml

jwt:
  refreshTokenExpirationMs: 2592000000

